# Generated by Django 5.0.1 on 2024-02-03 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('status', models.SmallIntegerField(choices=[(0, 'Idle'), (1, 'Running'), (2, 'Completed'), (3, 'Failed')], default=0)),
                ('os_type', models.IntegerField(blank=True, choices=[(1, 'CentOS'), (2, 'Ubuntu')], null=True)),
                ('os_version', models.CharField(blank=True, max_length=50, null=True)),
                ('err_msg', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'host_config',
            },
        ),
    ]
